/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as ListYourPropertyRouteImport } from './routes/list-your-property'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as ApiWebhooksTelegramCallbackRouteImport } from './routes/api/webhooks/telegram-callback'
import { Route as ApiWebhooksListingSubmittedRouteImport } from './routes/api/webhooks/listing-submitted'
import { Route as ApiPublicContactListingIdRouteImport } from './routes/api/public/contact.$listingId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourPropertyRoute = ListYourPropertyRouteImport.update({
  id: '/list-your-property',
  path: '/list-your-property',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ListingsRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksTelegramCallbackRoute =
  ApiWebhooksTelegramCallbackRouteImport.update({
    id: '/api/webhooks/telegram-callback',
    path: '/api/webhooks/telegram-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksListingSubmittedRoute =
  ApiWebhooksListingSubmittedRouteImport.update({
    id: '/api/webhooks/listing-submitted',
    path: '/api/webhooks/listing-submitted',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactListingIdRoute =
  ApiPublicContactListingIdRouteImport.update({
    id: '/api/public/contact/$listingId',
    path: '/api/public/contact/$listingId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/listings': typeof ListingsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/review': typeof AdminReviewRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/listing-submitted': typeof ApiWebhooksListingSubmittedRoute
  '/api/webhooks/telegram-callback': typeof ApiWebhooksTelegramCallbackRoute
  '/api/public/contact/$listingId': typeof ApiPublicContactListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/listings': typeof ListingsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/review': typeof AdminReviewRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/webhooks/listing-submitted': typeof ApiWebhooksListingSubmittedRoute
  '/api/webhooks/telegram-callback': typeof ApiWebhooksTelegramCallbackRoute
  '/api/public/contact/$listingId': typeof ApiPublicContactListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/list-your-property': typeof ListYourPropertyRoute
  '/listings': typeof ListingsRouteWithChildren
  '/submit': typeof SubmitRoute
  '/admin/review': typeof AdminReviewRoute
  '/listings/$id': typeof ListingsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/listing-submitted': typeof ApiWebhooksListingSubmittedRoute
  '/api/webhooks/telegram-callback': typeof ApiWebhooksTelegramCallbackRoute
  '/api/public/contact/$listingId': typeof ApiPublicContactListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compare'
    | '/list-your-property'
    | '/listings'
    | '/submit'
    | '/admin/review'
    | '/listings/$id'
    | '/admin/'
    | '/api/webhooks/listing-submitted'
    | '/api/webhooks/telegram-callback'
    | '/api/public/contact/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/list-your-property'
    | '/listings'
    | '/submit'
    | '/admin/review'
    | '/listings/$id'
    | '/admin'
    | '/api/webhooks/listing-submitted'
    | '/api/webhooks/telegram-callback'
    | '/api/public/contact/$listingId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compare'
    | '/list-your-property'
    | '/listings'
    | '/submit'
    | '/admin/review'
    | '/listings/$id'
    | '/admin/'
    | '/api/webhooks/listing-submitted'
    | '/api/webhooks/telegram-callback'
    | '/api/public/contact/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  ListYourPropertyRoute: typeof ListYourPropertyRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  SubmitRoute: typeof SubmitRoute
  ApiWebhooksListingSubmittedRoute: typeof ApiWebhooksListingSubmittedRoute
  ApiWebhooksTelegramCallbackRoute: typeof ApiWebhooksTelegramCallbackRoute
  ApiPublicContactListingIdRoute: typeof ApiPublicContactListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-property': {
      id: '/list-your-property'
      path: '/list-your-property'
      fullPath: '/list-your-property'
      preLoaderRoute: typeof ListYourPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/telegram-callback': {
      id: '/api/webhooks/telegram-callback'
      path: '/api/webhooks/telegram-callback'
      fullPath: '/api/webhooks/telegram-callback'
      preLoaderRoute: typeof ApiWebhooksTelegramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/listing-submitted': {
      id: '/api/webhooks/listing-submitted'
      path: '/api/webhooks/listing-submitted'
      fullPath: '/api/webhooks/listing-submitted'
      preLoaderRoute: typeof ApiWebhooksListingSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact/$listingId': {
      id: '/api/public/contact/$listingId'
      path: '/api/public/contact/$listingId'
      fullPath: '/api/public/contact/$listingId'
      preLoaderRoute: typeof ApiPublicContactListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminReviewRoute: typeof AdminReviewRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReviewRoute: AdminReviewRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ListingsRouteChildren {
  ListingsIdRoute: typeof ListingsIdRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsIdRoute: ListingsIdRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  ListYourPropertyRoute: ListYourPropertyRoute,
  ListingsRoute: ListingsRouteWithChildren,
  SubmitRoute: SubmitRoute,
  ApiWebhooksListingSubmittedRoute: ApiWebhooksListingSubmittedRoute,
  ApiWebhooksTelegramCallbackRoute: ApiWebhooksTelegramCallbackRoute,
  ApiPublicContactListingIdRoute: ApiPublicContactListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
